### ISSUE TITLE
Plz check my 13, 14 pract.

### ISSUE THREAD

**Issue by Flat1488** [kotsolesya/OPtaAM_PS_2015#43]
https://github.com/Flat1488/OPtaAM_PS_2015/tree/master/Varich/13%20pract
https://github.com/Flat1488/OPtaAM_PS_2015/tree/master/Varich/14%20pract

**Comment by kotsolesya** [comment]
що то за 13? ))))))

**Comment by Flat1488** [comment]
Молю вас, засчитайте пожалуйста
