### ISSUE TITLE
Сортировки

### ISSUE THREAD

**Issue by Attiny2000** [kotsolesya/OPtaAM_PS_2015#65]
https://github.com/Attiny2000/Sorting/blob/master/Program.cs
Все сортировки и время их выполнения

**Comment by kotsolesya** [comment]
Добав результат роботи відповідно до завдання

**Comment by Attiny2000** [comment]
![image](https://user-images.githubusercontent.com/26658198/35931479-6f2594b2-0c3d-11e8-914a-21646f45aaa4.png)
